replicaCount: 1
namespace: hello-world
image:
  repository: kcwan18/test-app
  pullPolicy: Always
  tag: sha256:6b6e82782fac45f279140e7b4e2c4afdeeb28b36bc342dd51791a54c5e4e47d3
container:
  port: 8080
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  name: helloworld-service
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  annotations: null
  hosts:
    - host: testapp2.k8s.dev.one2cloud.co
      paths:
        - path: /
          backend:
            serviceName: helloworld-service
            servicePort: 8005
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
