replicaCount: 1
namespace: hello-world
image:
  repository: kcwan18/test-app
  pullPolicy: Always
  tag: sha256:ff0d06ec4f17fe9522e52b1447840dda435438b5e692f146b9f9321dd575b7a5
container:
  port: 8080
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  name: helloworld-service
  type: ClusterIP
  port: 80
ingress:
  enabled: flase
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  # hosts:
  #   - host: testapp2.k8s.dedrive.io
  #     paths:
  #       - path: /
  #         backend:
  #           serviceName: helloworld-service
  #           servicePort: 8005
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
