apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd-ns
  finalizers:
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps/
    repoURL: https://github.com/Kcwan18/argotest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true