apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  # name: {{ include "helloworld-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.name }}
  labels:
    {{- include "helloworld-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helloworld-chart.selectorLabels" . | nindent 4 }}
